apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-multi-env-configmap
  namespace: {{ .Values.namespace }}
data:
{{ printf "environments/configmap.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}
