apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-multi-env-{{ .Values.namespace }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Values.namespace }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: helm-multi-env-{{ .Values.namespace }}-svc
                port:
                  number: 80
