apiVersion: v1
kind: Service
metadata:
  name: helm-multi-env-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: helm-multi-env
    env: {{ .Values.environment }}
